% Beamer slide template prepared by Tom Clark <tom.clark@op.ac.nz>
% Otago Polytechnic
% Dec 2012

\documentclass[10pt]{beamer}
\usetheme{Dunedin}
\usepackage{graphicx}
\usepackage{fancyvrb}

\newcommand\codeHighlight[1]{\textcolor[rgb]{1,0,0}{\textbf{#1}}}

\title{Exceptions and Exception Handling}

\author[IN608]{Intermediate Application Development}
\institute[Otago Polytechnic]{
  Otago Polytechnic \\
  Dunedin, New Zealand \\
  Kaiako: Tom Clark
}
\date{}
\begin{document}

%----------- titlepage ----------------------------------------------%
\begin{frame}[plain]
  \titlepage
\end{frame}

%----------- slide --------------------------------------------------%
\begin{frame}[fragile]
  \frametitle{The Problem}
  
  You may have noticed that things don't always go quite to plan when
  programming.
  
  \vspace{5mm}
  \begin{verbatim}
    def get_item(i):
        stuff = [1, 2, 3, 4, 5]
        return stuff[i]
  \end{verbatim}
  
  \vspace{5mm}
  What could possibly go wrong?
        
\end{frame}

%----------- slide --------------------------------------------------%
\begin{frame}[fragile]
  \frametitle{One Solution}
  
  If the argument \texttt{i} is not a valid index for our list, we're
  going to get an error. We can add some tests.
    
  \vspace{5mm}
  \begin{verbatim}
    def get_item(i):
        stuff = [1, 2, 3, 4, 5]
        if type(i) is int and 0 <= i and i < len(stuff):
            return stuff[i]
        else:
            return None    
  \end{verbatim}
  
  \vspace{5mm}
  This is ok, but now we've devoted a good chunk of our login to handling 
  cases that we don't expect to happen - to \emph{exceptional} cases.
\end{frame}

%----------- slide --------------------------------------------------%
\begin{frame}[fragile]
  \frametitle{Exceptions}
  
  Many programming languages deal with this by providing \emph{Exceptions}, a 
  sort of built in event and event handling to deal with these error cases.    
  \vspace{5mm}
  \begin{verbatim}
    def get_item(i):
        stuff = [1, 2, 3, 4, 5]
        return stuff[i]
          
  \end{verbatim}
  
  \vspace{5mm}
  \begin{itemize}
    \item If the argument \texttt{i} is not an integer, A \texttt{TypeError} is raised.
    \item If \texttt{i} is an integer outside the range of valid indices for our list, an \texttt{IndexError} 
    is raised.
  \end{itemize}  
   
\end{frame}

%----------- slide --------------------------------------------------%
\begin{frame}[fragile]
  \frametitle{One Solution}
  
  If the argument \texttt{i} is not a valid index for our list, we're
  going to get an error. We can add some tests.
    
  \vspace{5mm}
  \begin{verbatim}
    def get_item(i):
        stuff = [1, 2, 3, 4, 5]
        if type(i) is int and 0 <= i and i < len(stuff):
            return stuff[i]
        else:
            return None    
  \end{verbatim}
  
  \vspace{5mm}
  This is ok, but now we've devoted a good chunk of our login to handling 
  cases that we don't expect to happen - to \emph{exceptional} cases.
\end{frame}

%----------- slide --------------------------------------------------%
\begin{frame}[fragile]
  \frametitle{Exception Handling}
  
  Basic exception handling is done with a \texttt{try/except} block.
  
  \vspace{5mm}
  \begin{verbatim}
    def get_item(i):
        stuff = [1, 2, 3, 4, 5]
        try:
            return stuff[i]
        except IndexError:
            return None    
  \end{verbatim}
  
  \vspace{5mm}
  Notice that we're not handling the possible \texttt{TypeError}. If you don't have a 
  plan for how to recover from an exception, let it propagate.
   
\end{frame}

%----------- slide --------------------------------------------------%
\begin{frame}[fragile]
  \frametitle{Exception Handling}
  
  We can access the Exception object created when the error occured.
  
  \vspace{5mm}
  \begin{verbatim}
    def get_item(i):
        stuff = [1, 2, 3, 4, 5]
        try:
            return stuff[i]
        except IndexError:
            return None
        except TypeError as e:
            logger.error(e)
            raise e        
  \end{verbatim}
  
  \vspace{5mm}
  We also have the opportunity to take some action in the case of an exception and then 
  re-raise it to pass it up the stack.
   
\end{frame}


%----------- slide --------------------------------------------------%
\begin{frame}[fragile]
  \frametitle{Full try/except structure}
  

  \begin{verbatim}
    try:
        ...code...
    except ErrorType:
        ...handle ErrorType...
    except AnotherError as e:
        ...handle AnotherError with access to exception
    else:
        ...executed if no exceptions are raised...
    finally:
        ...aways executed after all other blocks complete...                
  \end{verbatim}
  
  \vspace{5mm}
  \end{frame}

%----------- slide --------------------------------------------------%
\begin{frame}
  \frametitle{Programming Activity}
  
  \begin{enumerate}
    \item Pull the course materials repo.
    \item Create a new branch, \texttt{05-practical} in your practicals repo.
    \item Add a subdirectory,  \texttt{05-practical} and copy \texttt{04-practical.ipynb} from the class materials into it.
    \item Open a shell, cd to this directory, and run \texttt{jupyter notebook} to open the notebook. Complete the first questions.
    \item We will discuss results in 30ish minutes.
  \end{enumerate}      
\end{frame}

%----------- slide --------------------------------------------------%
\begin{frame}
  \frametitle{User-defined Exceptions}
  
  \begin{enumerate}
    \item It's generally preferable to use a built in exception when it suits the error.
    \item Exceptions are just special classes.
    \item Exception names typically end in \texttt{Error}.
    \item A user-defined exception must derive from \texttt{Exception} or one of its subclasses.
    \item You can do just about anything, but in general they are simple classes that hold information about the error.
    \item User-defined exceptions must be explicitly raised in application code.
  \end{enumerate}      
\end{frame}




%----------- slide --------------------------------------------------%
\begin{frame}[fragile]
  \frametitle{Example}
  
      
  \begin{verbatim}
  class IN608Error(Exception):
      pass
      
  class InputError(IN608Error):
      def __init__(self, badinput, message):
          self.input = badinput  
          self.message = message
          
      def __str__(self):
          return f'InputError: {self.message}'      
                     
  \end{verbatim}           
  
\end{frame}

%----------- slide --------------------------------------------------%
\begin{frame}
  \frametitle{Conclusions}
  
  \begin{enumerate}
    \item Exceptions let us extract error handling from core logic.
    \item They are best used for handling things you don't expect to happen\footnote{There are notable counterexamples.}
    \item You don't have to handle every exception. It's generally bad practice to try. 
    \item Good reasons to handle exceptions include
      \begin{enumerate}
          \item It's possible to recover from the error and continue execution.
          \item The error in unrecoverable, but there are important actions to complete before halting execution.
      \end{enumerate}    
  \end{enumerate}      
\end{frame}


\end{document}
